In [ ]:
!pip install biopython

In [ ]:
from Bio import SeqIO

In [ ]:
from io import StringIO

data = """>Rosalind_23
AACCTTGG
>Rosalind_64
ACACTGTGA"""

elements = list(SeqIO.parse(StringIO(data), "fasta"))
elements

[SeqRecord(seq=Seq('AACCTTGG'), id='Rosalind_23', name='Rosalind_23', description='Rosalind_23', dbxrefs=[]),
 SeqRecord(seq=Seq('ACACTGTGA'), id='Rosalind_64', name='Rosalind_64', description='Rosalind_64', dbxrefs=[])]

In [ ]:
elements[0].seq, elements[1].seq

(Seq('AACCTTGG'), Seq('ACACTGTGA'))

```
  -AAC
- 0000
A 01 
C 0
A 0
```

(...)A, (...)A ===> (...) + 1

(...1)A, (...2)B ===> (...1), (...2)


In [ ]:
import numpy as np

FROM_UP = 10
FROM_LEFT = 20
FROM_DIAGONAL = 30

def lcs(seq1, seq2):
  cost = np.zeros((len(seq1) + 1, len(seq2) + 1))
  path = np.zeros(cost.shape)
  for j in range(1, len(seq1) + 1):
    for i in range(1, len(seq2) + 1):
      match = seq2[i - 1] == seq1[j - 1]
      cost[j][i] = max(cost[j - 1][i], cost[j][i-1], cost[j - 1][i-1] + match)
      if cost[j][i] == cost[j-1][i]:
        path[j][i] = FROM_UP
      elif cost[j][i] == cost[j][i - 1]:
        path[j][i] = FROM_LEFT
      else:
        path[j][i] = FROM_DIAGONAL

  return cost, path

In [ ]:
lcs("VANESSA","GUILHERME")

(array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0., 0., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0., 0., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0., 0., 1., 1., 1., 1.]]),
 array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
        [ 0., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
        [ 0., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
        [ 0., 10., 10., 10., 10., 10., 30., 20., 20., 20.],
        [ 0., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
        [ 0., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
        [ 0., 10., 10., 10., 10., 10., 10., 10., 10., 10.]]))

In [ ]:
lcs(elements[0].seq, elements[1].seq)

(array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [0., 1., 1., 2., 2., 2., 2., 2., 2., 2.],
        [0., 1., 2., 2., 3., 3., 3., 3., 3., 3.],
        [0., 1., 2., 2., 3., 3., 3., 3., 3., 3.],
        [0., 1., 2., 2., 3., 4., 4., 4., 4., 4.],
        [0., 1., 2., 2., 3., 4., 4., 5., 5., 5.],
        [0., 1., 2., 2., 3., 4., 5., 5., 6., 6.],
        [0., 1., 2., 2., 3., 4., 5., 5., 6., 6.]]),
 array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0., 30., 20., 20., 20., 20., 20., 20., 20., 20.],
        [ 0., 10., 10., 30., 20., 20., 20., 20., 20., 20.],
        [ 0., 10., 30., 10., 30., 20., 20., 20., 20., 20.],
        [ 0., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
        [ 0., 10., 10., 10., 10., 30., 20., 20., 20., 20.],
        [ 0., 10., 10., 10., 10., 10., 10., 30., 20., 20.],
        [ 0., 10., 10., 10., 10., 10., 30., 10., 30., 20.],
        [ 0., 10., 10., 10., 10., 10., 10., 10., 10., 10.]]))

In [ ]:
def print_lcs_path(path, seq1, seq2):
  i, j = len(seq1), len(seq2)
  content = ""
  # print(path)
  while i!=0 and j!=0:
    # print(i, j)
    if path[i][j] == FROM_LEFT:
      j -= 1
    elif path[i][j] == FROM_UP:
      i -= 1
    else:
      content += seq2[j - 1]
      i -= 1
      j -= 1
  return content[::-1]

print_lcs_path(lcs(elements[0].seq, elements[1].seq)[1], elements[0].seq, elements[1].seq)

'TTGTATCACCAGTTGTACCTGTGTAAATTACTCGGCATTTGGCGCGACGCCGTTTTTCGAGGACTCTGCTTAGATTCAGGTGGGGCGATAATGGAAAAGGGGGATAGCATTGTGTAGCCAGCTGTAAACTGGGTAATCCCAGGCTATAATCGCCAACACGAAGACGGTTTAGCGCAAATATCCATAGCGGGTACAAATTTGGCTGCGAGGGTCTGGTATCTTGCCGTCCTTTGGGTCCGTACCTGGAAGTTTGCCCAACACCAATACGATGTCGTCGAGAGTAAGAAAGATTTGGCTTTAAAACAGGATGCTCGCGTGTGGAGCCAAGCCCAGAAATCAGATCAAAGAGATCTCTGGGGTCCTTACATGCCGTGAGGGACCCTCTCACGCTAATTGTGCACTTACGCGACAAACCTGAGGCTTTAGAATGCAGAATCTGCGTATGCTCATACACGCATAGAGCATTGTCGTGTCGACTCACGCGATGGATTGATTGGGATGGCGGACCGTTTTACCGGTAATGCTACGGGGTTCTAGGATGTGTGACATGTTATGCTGGGAGATTTTAACGT'

In [ ]:
from io import StringIO

data = """>Rosalind_0882
CCCCTATTGTCGGTCAGGGGCGTCCTAAGGAAAAAGGCCCGCTATGACAACTGTGCGATT
GTCTCGCTGCCAGCGCCTTAAATAATCACACGACTCCCTGGAACTAATTTATGTGCGTGA
GAAAGGCGTTATCATTTCTTCACTTCTCCCATATGAAGGGTTTACGAGACAAGGTTATGC
ATGTTTGAACGTTCCTGCACTCTTACGGCTGCGGGATGTGTTAATATGTTCGCACGAAGC
CGGTTAGTAACAGGGCCTGATGCTTTACGGCAAGGTGTGTTCGCCCTCAGACGCGAGGAT
GTGGTGCCCGCCATTATCTGTCCGATAGCCGTGACCATGGCCTAGTTGATAAAGCCCGAC
CTGGATTTCGCCTGAGTTCCAATAAGCAGACAGTCGAAGATGCTCGAGACCATTTATGCA
AAGTTAGCAGCAAAATTCCCCTCAAAACCATCGCGTGGCCCCCGGAATCCCTCTCTCCGG
TCGGCACTCTGTTAGGTGAAAAACATACTGTACAGCCCAAGCAGGTCCACCAGTAAAGAG
AAGGGGGTCCTGGTCTTCTTCTGCAATAGATAGGCAGTTACGAGCTCCGAGTCGTCTTGT
TCAGAAGAAATTACTGTTCCAAAGTGCTGTAGCGTGTCCACACATCATAGCGCTGTTGGA
TGACGGAGCGCGTACTCGCATGTTGTCTTATCAGGTTTACTAACTAATCGCACGTTCGTG
TCAAATCGTGAGTATCATTCAAGCGACCGAACTTGAGGTTCCTTACAAATGGATAGTTTC
CCACAGATACCTGGCATATCTTCCTGCGATCGCTATGGACACTGATAAACGCACGGAATA
CCATCTTGCCTTTCCGTCAGAGCCTGCTAGCAATTGACGTTAAACAGTGCTTCAGTTTCA
TTGCTTTCTCGGGTGACGAAGCCACCCCTGTGCTTCGGACGATCCAAGAAAGGGGTC
>Rosalind_0455
GTTTACAATCCAGACGTACCACTTCCGATTATACTCTGACGAGATATAGCTGCCGTCCAG
GCCAAGAACTCGGCATCAGGAAAGCTCAACCTACCAGGAGCAGCGAAATCTTCATAAGGT
TTGCATGCGCGCCTTTAACACTTGGCTTACATACAACAATCTGGGCTCGTGGGAAGTATA
CTAAGTCCGGAGCAAGCAAGGAGTATGTACAGTAAAACGTTAAAAGTCGTGGGTAACGTT
ACCCATTTATAATATGCTAAGGGATATGCGCTAGATTCTAAGCTTTTTAAACAGGCATAT
CCCAATACAAGATGACCATCGAAACAATCCTTGAGGCTTGCTTCCAAACTACAAAACACA
TCAGTTAATCTGCACTTGCCGACCCGGGGGTACGAAAAACGGTCAGGGAACGCAATCCTC
CGCACGCACGCTACGAGGGGGTCTGGCCCAGGCGTGCAGGACGCTAGGACGGGGCGTCGT
AAGGAAATTACCGGGCGGAAGATATGAGGGGAGCCTTGCCGCTGTCCGCCGTTGATCCCC
GACAAAGGTAGACAATTGGACAACAAGCTAAATGTTCCCCGGCGAGTACACGGTAGAAAT
GTACTCTGTCTTGTATTATCACACCGAGTCCGACATGTAGGCACATGGTTACCTCCATCA
TAGCAAACTATTACCTACAACGTTCGACACGTTATAGGCACTCGCCTCCATATTCTCCCT
TGCATGGGCTAGTTCGTGGTACCGACTGGAGATGTCCATTAGACTTATCCTTGCGTACTT
CGGGCTCTTGCCAATTGGGTGAGGCGAGCGAAGGGAGGCGCTAGCGCAGTCGCCGAATAG
CAGCGGCGTGCCGATTATGGAGGCGTAGGCCCGCTCTTTTCCCAAC
"""

elements = list(SeqIO.parse(StringIO(data), "fasta"))
elements

[SeqRecord(seq=Seq('CCCCTATTGTCGGTCAGGGGCGTCCTAAGGAAAAAGGCCCGCTATGACAACTGT...GTC'), id='Rosalind_0882', name='Rosalind_0882', description='Rosalind_0882', dbxrefs=[]),
 SeqRecord(seq=Seq('GTTTACAATCCAGACGTACCACTTCCGATTATACTCTGACGAGATATAGCTGCC...AAC'), id='Rosalind_0455', name='Rosalind_0455', description='Rosalind_0455', dbxrefs=[])]

In [ ]:
print_lcs_path(lcs(elements[0].seq, elements[1].seq)[1], elements[0].seq, elements[1].seq)

'TTTCTCAGCGTCCACCCGTATACCTGCGATTGCTCGTCCAGGCCAAAATCCACAGGAACTAATACGGAGAGCGAATCTTCATAAGGTTTCAGCGGTTACATTGCTTCTCACTCTGGCTCGGGGAATATACAAGCCGGAGAACAGGGTATGTACGAAGTTGTCGTGGGAAGTTCCCATTATTGCTAGGGAATGGCTAGTTTAAGCTTTTCGCTATCCAATAAGAGACATCGAAACAACCTTAGCTTGCCAAACTCAAAACCATCGCTGCCCCGACCCGGGGGTAGAAAAACGTCAGAAGCATCCACCAGTAGAGGGGGTCTGGCCCGCGTGCAGACGCTGAGCGTCGTAAGAAATTACGCAAATTGAGGGACCTTGCGCTGTTGATGACGGAGCGGACCGCATGTTGCTACAGGTAAAATGACTCTGTCTGTATATCACACGACCGAATTAGGCACATGGTATCCACATAGCATATTCCTCACGTTGACACTATAACGCCTCCATTTCCTTGCAGGGCTAGTTCGTTAACAGTGCTTAGTTTCTTGCTTTCTCGGGTGACGAAGCCACCCCGTGCCGGCGTCCAAGAAGGGTC'

In [ ]:
print_lcs_path(lcs("GUILHERME", "VANESSA")[1], "GUILHERME", "VANESSA")

'E'

In [ ]:
print_lcs_path(lcs("CARDOSO", "VANESSA")[1], "CARDOSO", "VANESSA")

'AS'

In [ ]:
print_lcs_path(lcs("VANESSA", "GUILHERME")[1], "VANESSA", "GUILHERME")

'E'

In [ ]:
print_lcs_path(lcs("VA", "VANESSA")[1], "VA", "VANESSA")

'VA'

In [ ]:
print_lcs_path(lcs("VA", "AVANESSA")[1], "VA", "AVANESSA")

'VA'

In [ ]:
print_lcs_path(lcs("DA", "AVANESSDA")[1], "DA", "AVANESSDA")

'DA'